Update yas + snippets

diff --git a/git_template/src/block_master b/git_template/src/block_master
--- a/git_template/src/block_master
+++ b/git_template/src/block_master
@@ -1,8 +1,13 @@
 [ ! -z "${GIT_ALLOW_MASTER}" ] && exit 0
 
 if test $(git rev-parse --abbrev-ref HEAD) = "master" ; then
-    echo -e "Cannot commit to master by default.\nIf you really think want to then do\n\n\tGIT_ALLOW_MASTER=1 git commit\n"
-    exit 1
+  # NOTE: prompt matches default magit-process-yes-or-no-prompt-regexp
+  printf "Cannot commit to master by default. Override (y|n)? "
+  read -k 1 yn
+  case $yn in
+    [Yy]) exit 0;;
+    *) printf "\r\nAborted. Set GIT_ALLOW_MASTER=1 to skip this check.\n"; exit 1;;
+  esac
 fi
 
 # Local Variables:
